# Netlify configration

[build]

    base = "captcha"
    
    publish = "dist/"

    command = "npm run build"

    # for react-route redirect

    [[redirects]]

        from = "/*"

        to = "/index.html"

        status = 200
    
